# Generated by Django 2.0.4 on 2018-04-22 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('flag', models.CharField(default='yctf{F1ag_H3r3!}', max_length=30, verbose_name='FLAG')),
                ('subject_addr', models.CharField(blank=True, default='https://yoki.cloud/', max_length=50, null=True)),
                ('answer_number', models.IntegerField(default=0, verbose_name='解答数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_answer_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subjectPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=30)),
                ('package_content', models.TextField(verbose_name='包介绍')),
                ('package_include', models.ManyToManyField(to='index.subject')),
            ],
        ),
        migrations.CreateModel(
            name='subjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='subjectpackage',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.subjectType'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.subjectType'),
        ),
    ]
